### ISSUE TITLE
Request to add Biqu B1 printer to USB Driver

### ISSUE THREAD

**Issue by Nha-Krul** [feelfreelinux/octo4a#10]
First I want to thank you for the grate work that you are doing.
I want to ask if you can add the Biqu B1 printer to de USB Driver.
VID: 0x1D50 (OpenMoko, Inc.)
PID: 0x6029 (Marlin 2.0 (Serial))

Thanks

**Comment by feelfreelinux** [comment]
Will add the printer with a new update, thanks for letting me know :)

**Comment by SamuelRilling** [comment]
I absolutely love the project!
However i can't connect due to the "Printer not connected" error on my Anet A8, wonder if that could be implemented on a future update as well. Thanks in advance, keep up the good work!

**Comment by darranwil** [comment]
Thank you as well for this great package. I also would request the previously listed VID/PID be added.

**Comment by feelfreelinux** [comment]
Added in 1.0.0 :) https://github.com/feelfreelinux/octo4a/releases/tag/1.0.0
