### ISSUE TITLE
Android 7 TV box

### ISSUE THREAD

**Issue by Meguinness** [feelfreelinux/octo4a#104]
Installed octo with no problems, running smoothly and quick , the problem comes when starting the camera server. 
Sometimes the app will force close even before connecting a camera , and sometimes will work ok but once I reboot the TV box the octo app will not start unless I go to the app properties and disable camera permission.
Any possible solution? Thank you

**Comment by feelfreelinux** [comment]
Hi, is the camera a usb connected one?

**Comment by Meguinness** [comment]
Hi yes it is us... ..but the app still force close even without the camera been connected . I tried different ways, .... booting up with camera inserted in the usb port ...or without..., About 1 minute later it fill force close.
I believe the problem is some how related to permissions.....in attached photo when I tick DONT ASK AGAIN the allow button becomes unselectable. Thank you

**Comment by Meguinness** [comment]
![Uploading IMG_20211203_205356.jpg…]()

**Comment by Meguinness** [comment]
Hi yes it is us... ..but the app still force close even without the camera been connected . I tried different ways, .... booting up with camera inserted in the usb port ...or without..., About 1 minute later it fill force close.
I believe the problem is some how related to permissions.....in attached photo when I tick DONT ASK AGAIN the allow button becomes unselectable. Thank you
![Uploading IMG_20211203_205356.jpg…]()

**Comment by emailcraigs** [comment]
Did you ever get to the bottom of this? I'm having the same issue. Using USB cam. When enabling the Camera server it crashes and then I have to clear data and cache and reinstall before it will work again.

**Comment by pestregen** [comment]
> Did you ever get to the bottom of this? I'm having the same issue. Using USB cam. When enabling the Camera server it crashes and then I have to clear data and cache and reinstall before it will work again.

I have the same issue with a Android 11 TV-Box.

**Comment by Meguinness** [comment]
I was tired of the reliability issues so  I purchased a raspberry pi and using a hold Android phone as a IP webcam.

**Comment by alufers** [comment]
It should be fixed in >=1.2.1. There was an issue when there were 0 cameras in the device.
