### ISSUE TITLE
在电视盒上使用，每次开机都跳出来需要授权访问USB

### ISSUE THREAD

**Issue by dgpower** [feelfreelinux/octo4a#12]

**Comment by dgpower** [comment]
我用H96 pro TV BOX安装了你的app，并设定为开机自动启动，这样我就可以脱离电视机屏幕，让app自动工作。
但是，每次开机，app都会跳出一个窗口出来询问：是否允许访问USB设备。这导致了我必须接上电视机和键盘来处理这个问题。

I installed your app with H96 pro TV BOX and set it to start automatically after booting, so that I can leave the TV screen and let the app work automatically.
However, every time you boot up, the app will pop up a window asking whether to allow access to the USB device. This resulted in me having to connect the TV and keyboard to deal with this problem.

**Comment by ferrets6** [comment]
I had the same problem.
As a workaround, I use Automate with this flow

![image](https://user-images.githubusercontent.com/17033305/121775868-3a5c8780-cb8a-11eb-9104-e5e4d0d4db7e.png)

1. Start octo4a
2. Inspect layout change
![image](https://user-images.githubusercontent.com/17033305/121775884-552efc00-cb8a-11eb-8d10-d8f6474a019e.png)
![image](https://user-images.githubusercontent.com/17033305/121775942-a63ef000-cb8a-11eb-9278-aba914858cb4.png)
In this step, Automate wait for the SystemUI popup to show
3. Click the "Ok" button
![image](https://user-images.githubusercontent.com/17033305/121775949-b525a280-cb8a-11eb-9f88-5699105c495a.png)
![image](https://user-images.githubusercontent.com/17033305/121775960-beaf0a80-cb8a-11eb-8c46-9d084d7e160d.png)

If you don't know Automate, it's a very powerfull app!

**Comment by xiongyanbo** [comment]
> 我用H96 pro TV BOX安装了你的app，并设定为开机自动启动，这样我就可以脱离电视机屏幕，让app自动工作。
> 但是，每次开机，app都会跳出一个窗口出来询问：是否允许访问USB设备。这导致了我必须接上电视机和键盘来处理这个问题。
> 
> I installed your app with H96 pro TV BOX and set it to start automatically after booting, so that I can leave the TV screen and let the app work automatically.
> However, every time you boot up, the app will pop up a window asking whether to allow access to the USB device. This resulted in me having to connect the TV and keyboard to deal with this problem.
> ![4](https://user-images.githubusercontent.com/23353724/118355706-0babbb00-b5a4-11eb-853e-1f28aaf34af3.jpg)
> ![1](https://user-images.githubusercontent.com/23353724/118355716-16fee680-b5a4-11eb-8dca-caec84c36e92.jpg)

拔插一下usb有惊喜。
略微有点烦而已
我是用tasker做了自动点击。
最不好用的是上传文件会报错。实际是正常的。联机上传gcode会报500错误。实际上传成功。不会自动开始打印

**Comment by feelfreelinux** [comment]
Rewritten usb driver + auto boot option released in octo4a 1.0.0
