### ISSUE TITLE
Not connecting to BTT SKR Mini E3 via OTG cable

### ISSUE THREAD

**Issue by MsaterSgnt** [feelfreelinux/octo4a#128]
I'm trying to setup octo4a, but it keeps telling me that the printer is not connected. After looking at the FAQ, I saw a section for that there, but I'm not sure which option to use or how to implement it.

**Comment by MsaterSgnt** [comment]
It now tells me that it is connected via the cable, but the octoprint webpage will not connect to the printer

**Comment by joseph-montanez** [comment]
I got it working using the CDC option from the list of manual USB connections options. While it reports some /dev/usb/... it should still work. I'd recommend restarting Octoprint after you set the manual USB connection just in case. 

Do not if you have a complex OTG host with things like HDMI, Ethernet, etc you'll see a bunch of USB connection options, so you'll need to weed out which one is really for the USB port versus HDMI.

**Comment by SjamonDaal** [comment]
Works on my printer but it requires me to first turn on the printer and then connect it via OTG.

**Comment by eggandwaffles** [comment]
Changing the driver to CDC worked great for me as well, with no reboots or anything required. Thank you!

**Comment by manningcustom** [comment]
> 
can you explain what the cdc connection is?
