### ISSUE TITLE
Anet ET4 not supported?

### ISSUE THREAD

**Issue by sakirimren** [feelfreelinux/octo4a#13]
Hello,

When I connct my Anet ET4 (Marlin flashed) app says printer not connected.

**Comment by feelfreelinux** [comment]
Could you send me a screenshot from [this app](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal&hl=en&gl=US)'s device list? Thanks a lot :)

**Comment by pardovot** [comment]
@sakirimren I have Anet ET4 and it works fine.

**Comment by feelfreelinux** [comment]
Custom printer VID / PID without manually changing it added in 1.0.0. Thanks for reporting this :)
