### ISSUE TITLE
IP adress of octoserver changed after restarting phone.

### ISSUE THREAD

**Issue by rafds** [feelfreelinux/octo4a#153]
Hi, I've been using octoprint with success but after I restarted the phone octo4A suddenly changed the IP adress of the server. Not sure why and how can I revert to the old IP in the app?

**Comment by Chocorean** [comment]
In the mean time, you can edit your router config and assign a static IP address to your device so its local IP address won't change even after a reboot. This can also be done by doing a port forwarding on this device.

**Comment by alufers** [comment]
Unfortunately this is how DHCP works. You can adjust your router's settings to always assign the same IP to your phone.
