### ISSUE TITLE
Installation corrupted... But with a twist.

### ISSUE THREAD

**Issue by Negat1veZer** [feelfreelinux/octo4a#158]
Trying to install octo4a on my moto g pure, however 
I get the serialpipe error and the installation corrupted. I allowed access to managing files, i've tried 1.0.3, and I've tried reinstalling the software half a dozen times, but alas twas all for not. Any help would be greatly appreciated.
![Screenshot_20220210-235600](https://user-images.githubusercontent.com/99465356/153549264-9571c70c-dccb-4c34-b54b-55b206171442.png)
![Screenshot_20220210-235613](https://user-images.githubusercontent.com/99465356/153549268-0305898d-ba5c-4ae8-94e0-203e69a4b235.png)
![Screenshot_20220210-235741](https://user-images.githubusercontent.com/99465356/153549271-245018f4-27e7-43a9-8f7d-07268138288d.png)

**Comment by Negat1veZer** [comment]
As another side note, the app crashes as soon as it finishes loading. When I open it again it has the installation corrupted screen.

**Comment by miroan81** [comment]
Exactly the same problem on my Xperia z1, android 5.

**Comment by lpka** [comment]
the same problem, with Andorid 7 and andorid 10 on Galaxy tab s 8.4. formated the device, new install. same problem.

**Comment by miroan81** [comment]
Whats strange I also have lenovo with the same android 5 as z1, octo installed properly but the phone does not support OTG so I cant use that one.

**Comment by miroan81** [comment]
Octo is running fine now on my Z1 after I flashed custom android 10 fw. Anyone else wants this to work, go to xxda forums, flash your device with something  esle, you have nothing to lose but your time :) Good luck!

**Comment by stevvie** [comment]
Same ehere with Samsung Tab 4 with 1.1.1

**Comment by pnmartinez** [comment]
Same here on Xperia Z3, Android 6.

**Comment by HexRebuilt** [comment]
Same here with a Xiaomi Redmi pro, android 6

**Comment by alufers** [comment]
Should be fixed in the newest version (1.2.4). Please open another issue if its not.
