### ISSUE TITLE
Release camera when streaming not in use

### ISSUE THREAD

**Issue by ferrets6** [feelfreelinux/octo4a#17]
The two devices I tested (Sony Z3 Compact and tablet Samsung Note 10.1), the battery drains very fast when camera web server is on.

Would be wonderful to "release" the camera when no one is using the streaming. 

(see IP Webcam app by Pavel Khlebovich on Play Store for references)

**Comment by feelfreelinux** [comment]
Should be fixed in 1.0.0. Thanks for reporting this :)
