### ISSUE TITLE
not charging and sending data

### ISSUE THREAD

**Issue by JAbelP** [feelfreelinux/octo4a#186]
I have a tevo Tarantula pro and wanted to set up octoprint, I have both a LG G6 and a Samsung S7 I used [This charger](https://www.amazon.com/dp/B07FY9Z9GD?psc=1&ref=ppx_yo2ov_dt_b_product_details)  to connect to the printer, but I could only charge OR connect to the printer not both. I noticed when I did plug it in the LCD would turn on the printer. I went ahead and covered the 5V pin on the USB for the printer. I then used [This hub](https://www.amazon.com/dp/B00LTHBCNM?psc=1&ref=ppx_yo2ov_dt_b_product_details) , but same thing charge OR connect to the printer. But this one also had the added bonus of getting super hot. Do I need a power supply or something? do I have to do anything to enable charging OTG?

**Comment by alufers** [comment]
Hi, Thanks for trying octo4a!
Unfortunately some phones just don't support charging and using OTG at the same time :/
This is a known problem, and unfortunately it is near-impossible to solve on many phones.

We maintain a crowd-sourced compatibility list of phones which work with octo4a:
The list: https://docs.google.com/spreadsheets/d/1pbKAELzvTrMVm6NpDpK8TfQR33w3QHQEgqkcGdbPFI0/edit?usp=sharing
Feel free to submit your phone here: https://forms.gle/UFzJebj67hCtLCBz7

Sometimes it is possible to bypass this problem by trying these solutions:

- Using wireless charging. If your phone supports it, it might be possible to use a wireless charger and use the OTG feature at the same time. Some users have resorted to gluing a wireless charger to a phone case
  <img src="https://i.imgur.com/kUeGFCQ.png" height=300>
  
- Hard-wiring the battery. 
  **WARNING: CONNECTING A RANDOM POWER-SUPPLY STRAIGHT TO THE BATTERY MIGHT RESULT IN A FIRE OR EXPLOSION, EXERCISE EXTREME CAUTION** 
   Some people modify their phone to charge their battery externally, bypassing the phone's battery charging circuitry altogether. Some event removed the battery (the safest option)
   <img src="https://i.imgur.com/cT11K8o.png" height=300>
- Compiling a non-standard kernel. On some models the charging-and-OTG functionality is blocked in software, and this can be bypassed by using a non-stock kernel. Please be advised that compiling an Android kernel requires some skill and a lot of time.

If you need some guidance please feel free to ask on our telegram group: [(https://t.me/octo4achat)[]](https://t.me/octo4achat) . The community is very likely to help you.
