### ISSUE TITLE
Error Installing Octolapse Plugin

### ISSUE THREAD

**Issue by jjpl2001** [feelfreelinux/octo4a#187]
Hello. I have problems installing Octolapse on android devices.
I installed Plugin Extras

I tested Android 9 and installed normally on Android 12
Is there something I should install before installing Octolapse?
[plugin_pluginmanager_console_android9.log](https://github.com/feelfreelinux/octo4a/files/8500496/plugin_pluginmanager_console_android9.log)

**Comment by WRH0530** [comment]
I have the same problem

**Comment by WRH0530** [comment]
In the app, in the settings menu, there is an option called "install plugin extras"

**Comment by jjpl2001** [comment]
> 

I had try that many times without success, I made clean installs of the app several times.

What I can see in the install terminal is that there are a few errors during the install process.

**Comment by jjpl2001** [comment]
> In the app, in the settings menu, there is an option called "install plugin extras"

I had try that many times without success, I made clean installs of the app several times.
What I can see in the install terminal is that there are a few errors during the install process.

**Comment by bgross83** [comment]
Hello, same problem here on Xiaomi Mi 10 Lite with Android 12.
I get the error:

error: command 'gcc' failed: No such file or directory

**Comment by HunterDarkwolf** [comment]
The core of the issue for this is that OctoLapse requires the Python 3 dev kit to be installed.  It would help if it came bundled, especially since I would suspect that not a lot of people using this app are going to be able to work out how to install that on their phone.  Personally I'm currently attempting to install it as a downloaded plugin.  Because I'm not one of the ones software capable to install it through something like SSH to my phone.

**Comment by JustJerem** [comment]
Yeah, same problem on a Samsung Galaxy S8.
Did you found any work around @HunterDarkwolf  ? :)

**Comment by alufers** [comment]
![image](https://user-images.githubusercontent.com/5400940/194439654-7e530bbc-44a5-4686-82de-d5bdce20a48c.png)


Yes! Please use the "Install plugin extras" option before installing any plugins.

**Comment by kpostigo** [comment]
> Personally I'm currently attempting to install it as a downloaded plugin.

Were you able to get this to work?
