### ISSUE TITLE
Correct SSH Credentials

### ISSUE THREAD

**Issue by Manaswin07** [feelfreelinux/octo4a#19]
Hi, 
I am trying to ssh into the server, but I keep getting "connection refused" errors. It isn't working when I use the username I setup in octoprint using the browser either. From the app I can only see and set the ssh password. Kindly point me in the correct direction regarding this. 
Thanks!

**Comment by feelfreelinux** [comment]
Hi! I really should improve the ssh documentation :) In 0.0.5: use any username, for future releases: use 'octoprint' as username. Default ssh port is 8022 (same as termux)

**Comment by Manaswin07** [comment]
Hi! Thanks for the quick reply. This works well.

**Comment by MrDunham** [comment]
I'm reopening/commenting on this for the future semi-terminal literate people (like me) who are struggling with this.

To SSH in, open a terminal app (such as Terminal, on Mac)

Type:

ssh octoprint@localhost.local -p 8022

Enter the password you set when you turned on the SSH option on your Octo4a app (you did turn it on and set a password, right?)

Congratulations, you should now be in. Good luck and don't crater anything.

**Comment by Londonbingbang** [comment]
![image](https://user-images.githubusercontent.com/78421452/209416278-01929e9a-1628-46fd-b508-ddef8a76e7e4.png)
How do i fix this?

**Comment by mycream** [comment]
> ![image](https://user-images.githubusercontent.com/78421452/209416278-01929e9a-1628-46fd-b508-ddef8a76e7e4.png) How do i fix this?
> 
> I need help setting Octo4a up (having problems with "installation corrupted" dm me on discord Redstonenee#9739 if you can help thanks)

Change "localhost.local" to the IP which you mobile phone WIFI used. Make sure your computer connect to the same WIFI.
