### ISSUE TITLE
Recv: echo:busy: processing no printing 

### ISSUE THREAD

**Issue by Hallr841** [feelfreelinux/octo4a#191]
Recv: echo:busy: processing
Recv:  T:100.65 /0.00 B:47.88 /50.00 @:0 B@:39 W:?
Recv:  T:101.14 /0.00 B:45.54 /50.00 @:0 B@:127
Recv:  T:100.84 /0.00 B:46.61 /50.00 @:0 B@:127 W:?
Recv: echo:busy: processing
Recv:  T:100.76 /0.00 B:49.10 /50.00 @:0 B@:0 W:9
Recv:  T:101.18 /0.00 B:46.38 /50.00 @:0 B@:127
Recv:  T:100.53 /0.00 B:46.41 /50.00 @:0 B@:127 W:9
Recv: echo:busy: processing
Recv:  T:100.93 /0.00 B:47.50 /50.00 @:0 B@:127 W:9
Recv:  T:100.58 /0.00 B:47.76 /50.00 @:0 B@:127
Recv:  T:100.53 /0.00 B:49.46 /50.00 @:0 B@:0 W:8

using a pixel2 and that cr-10 v3, install octo4A  I can connect,
I can send a file, the bed will heat up and then nothing prints it just says
 there.

Recv: echo:busy: processing
Recv:  T:100.93 /0.00 B:47.50 /50.00 @:0 B@:127 W:9
Recv:  T:100.58 /0.00 B:47.76 /50.00 @:0 B@:127
Recv:  T:100.53 /0.00 B:49.46 /50.00 @:0 B@:0 W:8

 board rate auto
 111520

Is there any reason why I'm get this

**Comment by alufers** [comment]
It looks like a problem with octoprint, not octo4a :/
