### ISSUE TITLE
Question: After installing Octo4a 1.1.0…..”About” section in app still shows “octo4a build 1.0.4”?

### ISSUE THREAD

**Issue by wezxwezx** [feelfreelinux/octo4a#206]
Wasn’t sure if I did something wrong or it was just an oversight to change the “About” section to reflect the new build?

**Comment by feelfreelinux** [comment]
Ah my fault, fixed in new release :)

**Comment by wezxwezx** [comment]
I hope it didn’t sound like I was complaining! Just wanted to alert you to it…VERY appreciative of your efforts! Thank you!

**Comment by feelfreelinux** [comment]
> I hope it didn’t sound like I was complaining! Just wanted to alert you to it…VERY appreciative of your efforts! Thank you!

hah no problem, thanks a lot for heads up :) Glad the new release is of use for you!
