### ISSUE TITLE
OctoPrint fails to load in Web after upgrade to OctoPrint 1.8.0 & OctoPrint 4a 1.1.0

### ISSUE THREAD

**Issue by cjmorri1018** [feelfreelinux/octo4a#209]
@feelfreelinux

Similar to https://github.com/feelfreelinux/octo4a/issues/205#issuecomment-1131151561

I installed the new 1.1.0 version several hours ago, and rebooted several times while testing, and playing all seemed fine

The issue re-emerged briefly with same/similar message citing permissions at \dev when attempting to reboot after the re-install of a plugin. I had successfully uninstalled PSU Control plug in, rebooted successful, reinstalled PSU Control plugin and attempted restart - it displayed permissions /dev error on Windows 10 pc browser, the android 10 device browser interface displayed a message that I didnt catch. A restart of the app, and both browsers (pc and phone) seemed to clear it up.

In the process of attempting to recreate it I did a few uninstall and reinstalls of the same plug in, seemed fine, but when I did an uninstall & clean up data, then a re-install and reboot the issue returned. A restart of everything again, seems to clear it up again.

I noticed in both cases there has been messages to do with the Setting file or loading of the settings file. Let me know if you would like for me to recreate again and capture more/different info.

![image](https://user-images.githubusercontent.com/76878743/169333175-f76941dc-063d-4a8d-9b8f-2a0994201a59.png)

![image](https://user-images.githubusercontent.com/76878743/169333051-a9afd2db-d059-4900-ad35-02805270b252.png)

**Comment by sanebg** [comment]
I have the same exact issue with the same exact log for 3-4 versions. I cannot use it at all.

**Comment by sqcar** [comment]
I have the same exact issue with the same exact log for on android 8 /moto play  I cannot use it at all.

**Comment by Zodiase** [comment]
Just had the same error and it seems like installing https://github.com/feelfreelinux/octo4a/releases/tag/1.1.1 resolved the issue.

**Comment by cjmorri1018** [comment]
I installed 1.1.1 after this post and seems to be okay since.  

https://github.com/feelfreelinux/octo4a/releases/tag/1.1.1
