### ISSUE TITLE
issue with SSH

### ISSUE THREAD

**Issue by ghost** [feelfreelinux/octo4a#212]
So im trying to setup klipper for my voron 0.1, and none of the commands on the voron website will work

![Capture](https://user-images.githubusercontent.com/106206967/170153607-c40ace1d-1ea4-465c-8ab5-1f732c088e2c.PNG)

any help would be greatly appreciated

**Comment by parrotsgain** [comment]
different distros use different package mangers and usually different package names.
apt is for debian/ubuntu based
apk is for alpine. apk add **** or apk del *** and no sudo  
https://wiki.alpinelinux.org/wiki/Package_management

your home is in /root and /root/Octoprint-*****

**Comment by sheminasalam** [comment]
> 

Did you find get klipper to work? Do you have any guides?

**Comment by alufers** [comment]
Marking as solved by @parrotsgain
