### ISSUE TITLE
Expose battery level

### ISSUE THREAD

**Issue by Gerigot** [feelfreelinux/octo4a#217]
Is there a way to expose  through API or some script the battery level status so that, maybe with a plugin, being able to show it to the octoprint page, or connect it to the telegram plugin to have an alert when battery is about to run out.
I had a problem not so long ago that I forgot to close the webcam view in cura and my phone "died" in the middle of a print.

A part of that now It's almost 6 month since I started using Octo4a with my ender 3 v2 and it's working perfectly so I want to say thank you all for the great work.

**Comment by wjflier** [comment]
solder charge cable to phone

**Comment by Gerigot** [comment]
the problem it is not the charging system in this case, I'd like to have the battery level somehow exposed if it's possible.
My exemple was only a use case, I know there are some other solutions but it would be nice to see the battery level in octoprint.

**Comment by kilimar** [comment]
> solder charge cable to phone

Not everyone had the ability to solder (or the equipment or even the tools to open up the phone).  :-)

**Comment by miroan81** [comment]
You cant use this and rely only on a phone battery, its useless and impractical. You must either make or buy Y cable that will allow you to charge phone at the same time or soldier buck converter to a battery terminals. Y cable doesn't work with all phones but if it does its the most easiest solution

**Comment by Gerigot** [comment]
I know I wrote that my phone is always in charge but the webcam sometimes uses more energy that the charger can give ... And, as i wrote, it's also a supplementary feature that can be used just for showing the charge, mine was only a use case.

**Comment by mramirkhan** [comment]
The Y cable isn't supported on many phones. Thankfully it is on mine but I had to install many many kernels until I found a setup that allowed it. It's a real problem, not one I face but never the less i do understand what OP is feeling.

**Comment by tobiasgraf** [comment]
I've hacked together a little plugin that exposes the battery level of the phone and can send telegram messages when battery is running low. Have a look here

https://github.com/tobiasgraf/OctoPrint-Octo4a_battery

**Comment by Gerigot** [comment]
your plugin is amazing thank you! that's exactly what I needed.
I will close this Issue.

**Comment by davidalim** [comment]
Anyone know the battery file path for Samsung Galaxy S5?

**Comment by davidalim** [comment]
I used ADB to browse to the file and it's actually there and has the battery percent. However still shows INVALID PATH.

**Comment by davidalim** [comment]
Yes totally. Didn't know much about these files so assumed it was just my phone or something :)

I'm running this on a Samsung Galaxy S5 with LineageOS 18.1 (Android 11). Not rooted. 

I did just install on my Galaxy S4 (running Pixel Experience 9) and it works! So personally no longer an urgent issue.

**Comment by aymaliev** [comment]
Solution:

I really wanted to get back the battery indicator for my Octo4a and found a workaround.
There is an app on Fdroid, which writes the battery percentage to an accessible location. The app is called BatteryDog.

I then forked and modified the original Octo4a_battery repo to read the new file.

> It works!

My fork can be found at: https://github.com/aymaliev/OctoPrint-Octo4a_battery.
