### ISSUE TITLE
Http 500 on prusaslicer 

### ISSUE THREAD

**Issue by Jack-thetube** [feelfreelinux/octo4a#218]
I tried to upload a gcode using prusaslicer (same thing on cura), but when I try it gives me the error http 500.
But when I try directly on octoprint all works!!!
So can anybody help me with that

**Comment by Gerigot** [comment]
I'm not using prusaslicer but on Cura I know that you have to pair the api key with our octoprint server.
If you go on Settings -> Printer -> manage printer and, selecting  your printer on the list, click on connect octoprint what do you see?
