### ISSUE TITLE
I can't connect to the server using browser.

### ISSUE THREAD

**Issue by Kaptus2137** [feelfreelinux/octo4a#219]
Hi I have a problem.  When I click on the ip on the phone everything works. But i can't connect to the server using  browser. Thank you in advance and best regards.

**Comment by miroan81** [comment]
How the IP in an app looks like 192.x.x.x OR 0.x.x.x ? If it starts with 0 then you're not connected to local wifi, if not make sure you put :5000 at the end

**Comment by Kaptus2137** [comment]
> How the IP in an app looks like 192.x.x.x OR 0.x.x.x ? If it starts with 0 then you're not connected to local wifi, if not make sure you put :5000 at the end

Its look normal start with 192.168.x.xxx:5000

**Comment by Kaptus2137** [comment]
Whent i click on ip in the app the octoprint control panel  is loding and works but when i want to conect to the server typing ip in my browser the site is loding loding and loding and then i get normal browser eror:






![Zrzut ekranu 2022-06-05 113528](https://user-images.githubusercontent.com/97808166/172044461-f953b6c0-0400-4280-8f0a-c7823ff58614.png)

**Comment by Kaptus2137** [comment]
When i click on ip in the app the octoprint control panel  is loding and works but when i want to conect to the server typing ip in my browser the site is loding loding and loding and then i get normal browser error:

![to ten](https://user-images.githubusercontent.com/97808166/172044595-ac5660ff-e166-4d4c-bf17-0b3f79a943cb.jpg)

**Comment by Gerigot** [comment]
Are you connected on the same network of the phone? if yes, as mentioned above, did you put the :5000 at the end of the url? for example, supposing your phone/server ip is 192.168.1.100 you should put: http://192.168.1.100:5000

**Comment by Kaptus2137** [comment]
Yup i put :5000. My computer and second wifi router are connect to the main router. Phone is conect to the secont router.

**Comment by Gerigot** [comment]
probably the problem lies there the fact that you are using two router try to check the subnetwork or try to see how can you make those two network speak with each other.
The main router and the second router are in the same network but the phone is in the second router's network not accessible from your compoter on the first router's network

**Comment by Kaptus2137** [comment]
Thx 
![obraz_2022-06-06_223553954](https://user-images.githubusercontent.com/97808166/172244366-645d9e25-5c2c-434d-8389-8770ccedc3e9.png)
