### ISSUE TITLE
App crashes when connected to wifi with no access to Internet

### ISSUE THREAD

**Issue by grizz0blaw** [feelfreelinux/octo4a#22]
I've successfully installed the app & it shows it's connected to the printer. However, that is when it's connected to my regular router that has access to the internet. When I switch to my other wifi router with no internet access, the app crashes. Does the app only work when it has access to the internet?

**Comment by alufers** [comment]
Yes, it needs to download octoprint and a few other things.

**Comment by feelfreelinux** [comment]
Since 1.0.0 octo4a warns about lack of internet connection before performing the install.
