### ISSUE TITLE
Nuu Mobile R1 does not work.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [feelfreelinux/octo4a#226]
The Nuu Mobile R1 is capable of doing OTG alongside charging but plugging it into the printer causes nothing to happen.

It looks like it might be a hardware issue but yeah, kinda of a bummer.

I thought [it was an octoprint issue and posted logs and everything over there.](https://community.octoprint.org/t/cr-30-on-octoprint4android/44946)

**Comment by WriteCodeEveryday** [comment]
![PXL_20220611_025708494 MP](https://user-images.githubusercontent.com/1066583/173170114-80c7740d-2f9b-40d6-8089-0ff8abc5ae34.jpg)

**Comment by alufers** [comment]
Hi, thanks for trying octo4a!

Please try connecting an USB mouse first. If a cursor doesn't appear this means this is a problem with the OTG cable or your phone does not support OTG.

Cheers!

PS: feel free to ping me if you need this issue to be re-opened
