### ISSUE TITLE
MiniX Neo X7 with Android 5.1.1

### ISSUE THREAD

**Issue by Gurbalur** [feelfreelinux/octo4a#240]
Seems to work fine but when restarting server on the MiniX via web on PC it uses the wrong IP so I have to restart the MiniX and Octo4a to get the right IP.

**Comment by Gurbalur** [comment]
Also no Web Cam. I have connected a Logitech C615 that is reported as an HD Webcam C615 but no matter serial port I choose I get no picture.

**Comment by alufers** [comment]
See also: #95 for webcam support.

**Comment by jovicassia** [comment]
no solution for USB camera (on TV BOX)?
