### ISSUE TITLE
USB OTG Not Connecting on ChromeOS

### ISSUE THREAD

**Issue by the-woj** [feelfreelinux/octo4a#243]
Hey all,

I know this project is specifically for Android, but I figured ChromeOS was basically just glorified Android and I found a relatively high spec ChromeOS tablet with OTG support for not too much money (Lenovo Chromebook Duet). I purchased a cheaper USB-C hub and then a USB OTG cable as well, but the app still can't see the printer--it just says in the start window to connect the printer through OTG when connected to either. Has anyone gotten this app working on ChromeOS before? The printer was showing up under USB devices in terminal.
 For reference, the printer is an ANet A8.

Oh, also the 'Chromebook' does not have a home button (I presume it's on the separate keyboard I don't own), and when I open the OctoPrint page I have no way of closing the app anymore.

Thanks!

**Comment by alufers** [comment]
Hi! I don't think that Android apps on ChromeOS have access to USB devices :/

You can try the Linux sandbox, and install Octoprint there (like you would on a Raspberry Pi): https://support.google.com/chromebook/answer/9145439

But I have no idea if it will work there too.
