### ISSUE TITLE
Issues with Android 11/12? 

### ISSUE THREAD

**Issue by cylemmulo-1** [feelfreelinux/octo4a#249]
Bought a blu view 2 with android 11 on it, and it only gives me the "corrupted installation" error. No sd card in the device. Tried in on my galaxy tab s8 with android 12 and it does the same thing.

**Comment by jester50158** [comment]
I have the same issue.  With the same phone. I have tried with an new SD, with out.

**Comment by cylemmulo-1** [comment]
> 

It's appearing like a Tracfone and other prepaid vendor issue with some sort of lockdown. I was told to look into boost phones.

**Comment by Pingnan** [comment]
Had anyone made any progress on this? I tried anything and still can not install octo4a on my blu view 2.

**Comment by jup2000** [comment]
Can confirm 1.1.1 does NOT install on the Tracfone Blu 2.

**Comment by jup2000** [comment]
Just purchased a brand new Cricket Moto G Pure running Android 11 with the exact same issue.  Bootstrap problem for ARM installs?

**Comment by alufers** [comment]
Hi! Could you post your logs here?

This will help us with debugging.
