### ISSUE TITLE
Jigsaw Button (Plugins?) Crashes App

### ISSUE THREAD

**Issue by RicME85** [feelfreelinux/octo4a#258]
Hi,
If I tap the jigsaw button (I assume this is plugins?) the app will instantly crash to the homescreen.

Nokia 6 TA-1033
Android 9
Nothing installed except Octo4a plus the in-app plugin extras. Phone was completely wiped and started fresh with Octo4a.

**Comment by alufers** [comment]
Did you install the plugin extras from the settings?

![image](https://user-images.githubusercontent.com/5400940/194437921-305cfc2b-72d9-4b81-8053-4095c375a865.png)

Please ping me to reopen this issue if the problem persists.
