### ISSUE TITLE
set hostname

### ISSUE THREAD

**Issue by mcmasterp** [feelfreelinux/octo4a#259]
I have roughly 50 printers in my farm and I use a hostname nomenclature to help organize them. I now have 2 T95 androidtv boxes with octo4a and it would be immensely helpful if I could set a hostname rather than use the IP address.

P.S. I just have to say thank you more than you can know. With the price of pi4 right now you have made a huge difference in my small business going forward

**Comment by alufers** [comment]
Hi! It's not possible to change the hostname of an Android device from an app.

You can try changing the device's name in Android settings, and see if it will help.
