### ISSUE TITLE
Build instructions 

### ISSUE THREAD

**Issue by mmiscool** [feelfreelinux/octo4a#27]
Hello,
Love the project. 
Am interested in making a customized version with some octoprint plugins preinstalled and configured. 
Any guidance on build instructions and packaging would be appreciated.

**Comment by feelfreelinux** [comment]
Hi! You should be able to achieve that by either editing the  installation script (https://github.com/feelfreelinux/octo4a/blob/master/app/app/src/main/java/com/octo4a/repository/OctoPrintHandlerRepository.kt#L93v) or by preparing a custom bootstrap linux rootfs. Hopefully I'll be able to implement some kind of init script customization with a new release.

**Comment by feelfreelinux** [comment]
With 1.0.0 you can achieve that by modyfing the initial `setup-octo4a.py` script, or implementing an extension https://github.com/feelfreelinux/octo4a/wiki/Extensions-system

**Comment by bzhmaddog** [comment]
I'd also like to be able to build the apk myself.

**Comment by feelfreelinux** [comment]
After a latest commit, the main branch can be built by just importing the subfolder app into Android Studio.
Github workflow: https://github.com/feelfreelinux/octo4a/blob/master/.github/workflows/build-app.yml

As for the underlying bootstrap:
Scripts required to build it are available in this repository: https://github.com/feelfreelinux/android-linux-bootstrap
There's also a github action workflow that builds and releases it in that repository.
