### ISSUE TITLE
PD charge - Type C Hub - Type C Phone

### ISSUE THREAD

**Issue by creationmz** [feelfreelinux/octo4a#273]
Hello,

I have this setup:

1 Anycubic 4Max Pro (full stock)
2 Baseus Type C USB3 HUB with PD charge port
3 Baseus Type C USB3 Charger >3Amps@5V
4 Noname QC3 Type A Charger >3Amps@5V
5 Baseus Type C to Type C PD cable
6 Essager Type A to Type C max100W cable
7 Huawei P30 with Android 12 expert mode ON
8 Redmi 9 with Android 10 expert mode ON

Results:
A HUB OK - a HUB NOK (it means, it can recognize anything what I plug in [SD, Pendrive... etc...])
B Charge OK - b Charge NOK
C Printer visible OK - c Printer not visible NOK
D Printer Connection OK - d Printer can not connect NOK

I've tried this connections:
72641 -> ABCD
72531 -> ABCD
P30 can work well
but R9...
82641 -> abcd
864 -> aBcd
821 -> AbCD
8264 -> aBcd
825 -> aBcd
82531 -> aBcd
If I disconnect the charger from the HUB, the octo4a recognize the printer instantly, but when I plug the charger again, the carging is not working (the printer is still have connection).

I've tried to cut the printer cabel "+" wire, but the same Issue.

Is anybody can help me? :)
Am I missing any settings on the Redmi9?

**Comment by alufers** [comment]
Hi, Thanks for trying octo4a!
Unfortunately some phones just don't support charging and using OTG at the same time :/
This is a known problem, and unfortunately it is near-impossible to solve on many phones.

We maintain a crowdsourced compatibility list of phones which work with octo4a:
The list: https://docs.google.com/spreadsheets/d/1pbKAELzvTrMVm6NpDpK8TfQR33w3QHQEgqkcGdbPFI0/edit?usp=sharing
Feel free to submit your phone here: https://forms.gle/UFzJebj67hCtLCBz7

Sometimes it is possible to bypass this problem by trying theese solutions:

- Using wirless charging. If your phone supports it, it might be possible to use a wireless charger and use the OTG feature at the same time. Some users have resorted to gluing a wirless charger to a phone case
  <img src="https://i.imgur.com/kUeGFCQ.png" height=300>
  
- Hard-wiring the battery. 
  **WARNING: CONNECTING A RANDOM POWER-SUPPLY STRAIGHT TO THE BATTERY MIGHT RESULT IN A FIRE OR EXPLOSION, EXERCISE EXTREME CAUTION** 
   Some people modify their phone to charge their battery externally, bypassing the phone's battery charging circutry alltogether. Some event removed the battery (the safest option)
   <img src="https://i.imgur.com/cT11K8o.png" height=300>
- Compiling a non-standard kernel. On some models the charing-and-OTG functionality is blocked in software, and this can be bypassed by using a non-stock kernel. Please be advised that compiling an Android kernel requires some skill and a lot of time.

If you need some guidance please feel free to ask on our telegram group: (https://t.me/octo4achat)[https://t.me/octo4achat]. The community is very likely to help you.
