### ISSUE TITLE
SSH User not mentioned

### ISSUE THREAD

**Issue by greenbigfrog** [feelfreelinux/octo4a#274]
Hi,
I noticed the ssh settings don't mention the user. Checking the web tty interface showed root, so I just went ahead and tried that.
Perhaps it should just be listed in the modal under `Change SSH Password` as `Change SSH Password (User: root)?` I can open a PR if need be.

https://github.com/feelfreelinux/octo4a/blob/46b00618d59cb1481a0448212e432515e505a52d/app/app/src/main/res/xml/main_preferences.xml#L29

**Comment by alufers** [comment]
Label fixed, will be added in the next release.
