### ISSUE TITLE
charging

### ISSUE THREAD

**Issue by bkmac511** [feelfreelinux/octo4a#277]
My phone is charging my printer. Exactly. If anybody have solution please feel free to dm me or mention here
setup:
ender3 v2
galaxy s8+

![IMG20220915201807](https://user-images.githubusercontent.com/96415682/190480101-aa5c7223-9929-4900-a41e-f1c78720ba7f.jpg)

**Comment by alufers** [comment]
Hi!
Thanks for using octo4a.

Pleas consult this post on the octprint community forum: https://community.octoprint.org/t/put-tape-on-the-5v-pin-why-and-how/13574
