### ISSUE TITLE
Crash in Install v1.1.1 (and older)

### ISSUE THREAD

**Issue by darkza** [feelfreelinux/octo4a#284]
Deleted Log a bit because to much Charakters. >
![Screenshot_20220925-093402](https://user-images.githubusercontent.com/9936033/192133646-7f4450f7-b28c-4088-88b7-e18023f42986.png)

🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/test_daemon.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/test_events.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/test_octoprint_setuptools.py 
🐸    creating: OctoPrint-OctoPrint-d0d226f/tests/timelapse/
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/timelapse/__init__.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/timelapse/test_timelapse_helpers.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/timelapse/test_timelapse_renderjob.py 
🐸    creating: OctoPrint-OctoPrint-d0d226f/tests/util/
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/__init__.py 
🐸    creating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/
🐸    creating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/jinja_test_data/
🐸  extracting: OctoPrint-OctoPrint-d0d226f/tests/util/_files/jinja_test_data/.hidden_everywhere.txt 
🐸  extracting: OctoPrint-OctoPrint-d0d226f/tests/util/_files/jinja_test_data/normal_text.txt 
🐸  extracting: OctoPrint-OctoPrint-d0d226f/tests/util/_files/jinja_test_data/not_a_text.dat 
🐸    creating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/already_installed_1.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/already_installed_2.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/egg_problem_1.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/egg_problem_2.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/python_mismatch_1.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/python_mismatch_2.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/pip_test_data/successful_install_1.txt 
🐸  extracting: OctoPrint-OctoPrint-d0d226f/tests/util/_files/utf8_with_bom.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/_files/utf8_without_bom.txt 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_caseinsensitive_set.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_comm.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_comm_helpers.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_commandline.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_counted_event.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_fast_deepcopy.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_file_helpers.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_files.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_jinja.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_json.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_misc.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_net.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_pip.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_platform.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_repeated_timer.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_resettable_timer.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_string_helpers.py 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/tests/util/test_version.py 
🐸    creating: OctoPrint-OctoPrint-d0d226f/translations/
🐸    creating: OctoPrint-OctoPrint-d0d226f/translations/de/
🐸    creating: OctoPrint-OctoPrint-d0d226f/translations/de/LC_MESSAGES/
🐸   inflating: OctoPrint-OctoPrint-d0d226f/translations/de/LC_MESSAGES/messages.mo 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/translations/de/LC_MESSAGES/messages.po 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/translations/messages.pot 
🐸   inflating: OctoPrint-OctoPrint-d0d226f/versioneer.py 
🐸 proot warning: can't sanitize binding "/data/data/com.octo4a/files/serialpipe": No such file or directory
🐸 Processing /root/OctoPrint-OctoPrint-d0d226f
🐸 Collecting OctoPrint-FileCheck>=2021.2.23
🐸   Downloading OctoPrint_FileCheck-2021.2.23-py2.py3-none-any.whl (19 kB)
🐸 Collecting OctoPrint-FirmwareCheck>=2021.10.11
🐸   Downloading OctoPrint_FirmwareCheck-2021.10.11-py2.py3-none-any.whl (33 kB)
🐸 Collecting OctoPrint-PiSupport>=2022.3.28
🐸   Downloading OctoPrint_PiSupport-2022.6.13-py2.py3-none-any.whl (33 kB)
🐸 Collecting argon2_cffi<22,>=21.3.0
🐸   Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
🐸 Collecting cachelib<0.3,>=0.2
🐸   Downloading cachelib-0.2.0-py3-none-any.whl (12 kB)
🐸 Collecting Click<9,>=8.0.3
🐸   Downloading click-8.1.3-py3-none-any.whl (96 kB)
🐸 Collecting colorlog<7,>=6
🐸   Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
🐸 Collecting emoji<2,>=1.4.2
🐸   Downloading emoji-1.7.0.tar.gz (175 kB)
🐸 Collecting feedparser<7,>=6.0.8
🐸   Downloading feedparser-6.0.10-py3-none-any.whl (81 kB)
🐸 Collecting filetype<2,>=1.0.7
🐸   Downloading filetype-1.1.0-py2.py3-none-any.whl (17 kB)
🐸 Collecting Flask-Assets<3,>=2.0
🐸   Downloading Flask_Assets-2.0-py3-none-any.whl (8.5 kB)
🐸 Collecting Flask-Babel<3,>=2.0
🐸   Downloading Flask_Babel-2.0.0-py3-none-any.whl (9.3 kB)
🐸 Collecting Flask-Login<0.6,>=0.5
🐸   Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
🐸 Collecting Flask-Limiter<3,>=2.6
🐸   Downloading Flask_Limiter-2.6.3-py3-none-any.whl (25 kB)
🐸 Collecting flask<2.2,>=2.1
🐸   Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
🐸 Collecting frozendict<3,>=2.0
🐸   Downloading frozendict-2.3.4-py3-none-any.whl (11 kB)
🐸 Collecting future<1,>=0.18.2
🐸   Downloading future-0.18.2.tar.gz (829 kB)
🐸 Collecting markdown<4,>=3.2.2
🐸   Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
🐸 Collecting netaddr<0.9,>=0.8
🐸   Downloading netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
🐸 Requirement already satisfied: netifaces<1,>=0.11 in /usr/lib/python3.9/site-packages (from OctoPrint==1.8.3) (0.11.0)
🐸 Collecting passlib<2,>=1.7.4
🐸 Collecting pathvalidate<3,>=2.4.1
🐸   Downloading pathvalidate-2.5.2-py3-none-any.whl (20 kB)
🐸   Downloading pkginfo-1.8.3-py2.py3-none-any.whl (26 kB)
🐸 Requirement already satisfied: psutil<6,>=5.8 in /usr/lib/python3.9/site-packages (from OctoPrint==1.8.3) (5.8.0)
🐸 Collecting pylru<2,>=1.2
🐸   Downloading pylru-1.2.1-py3-none-any.whl (16 kB)
🐸 Collecting pyserial<4,>=3.4
🐸   Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
🐸 Collecting requests<3,>=2.26.0
🐸   Downloading requests-2.28.1-py3-none-any.whl (62 kB)
🐸 Collecting sarge==0.1.6
🐸   Downloading sarge-0.1.6.tar.gz (26 kB)
🐸 Collecting semantic_version<3,>=2.8.5
🐸   Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
🐸 Collecting sentry-sdk<2,>=1.5.7
🐸   Downloading sentry_sdk-1.9.8-py2.py3-none-any.whl (158 kB)
🐸   Downloading tornado-6.2.tar.gz (504 kB)
🐸   Installing build dependencies: started
🐸   Installing build dependencies: finished with status 'done'
🐸   Getting requirements to build wheel: started
🐸   Getting requirements to build wheel: finished with status 'done'
🐸     Preparing wheel metadata: started
🐸     Preparing wheel metadata: finished with status 'done'
🐸 Collecting watchdog<2,>=1
🐸   Downloading watchdog-1.0.2.tar.gz (98 kB)
🐸 Collecting websocket-client<2,>=1.2.1
🐸   Downloading websocket_client-1.4.1-py3-none-any.whl (55 kB)
🐸 Collecting werkzeug<2.1,>=2.0
🐸   Downloading Werkzeug-2.0.3-py3-none-any.whl (289 kB)
🐸 Collecting wrapt<1.14,>=1.13.3
🐸   Downloading wrapt-1.13.3.tar.gz (48 kB)
🐸 Collecting zeroconf<0.34,>=0.33
🐸   Downloading zeroconf-0.33.4-py3-none-any.whl (89 kB)
🐸 Collecting zipstream-ng<2.0.0,>=1.3.4
🐸   Downloading zipstream-ng-1.3.4.tar.gz (22 kB)
🐸 Collecting blinker<2,>=1.4
🐸   Downloading blinker-1.5-py2.py3-none-any.whl (12 kB)
🐸 Requirement already satisfied: regex in /usr/lib/python3.9/site-packages (from OctoPrint==1.8.3) (2021.4.4)
🐸 Collecting unidecode
🐸   Downloading Unidecode-1.3.4-py3-none-any.whl (235 kB)
🐸 Collecting argon2-cffi-bindings
🐸   Downloading argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
🐸   Installing build dependencies: started
🐸   Installing build dependencies: finished with status 'error'
🐸   ERROR: Command errored out with exit status 1:
🐸    command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gp9i1_7f/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45' 'setuptools_scm>=6.2' wheel 'cffi>=1.0.1'
🐸        cwd: None
🐸   Complete output (73 lines):
🐸   Collecting setuptools>=45
🐸     Using cached setuptools-65.4.0-py3-none-any.whl (1.2 MB)
🐸   Collecting setuptools_scm>=6.2
🐸     Downloading setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
🐸   Collecting wheel
🐸     Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
🐸   Collecting cffi>=1.0.1
🐸     Downloading cffi-1.15.1.tar.gz (508 kB)
🐸   Collecting pycparser
🐸     Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
🐸   Collecting packaging>=20.0
🐸     Downloading packaging-21.3-py3-none-any.whl (40 kB)
🐸   Collecting typing-extensions
🐸     Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
🐸   Collecting tomli>=1.0.0
🐸     Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
🐸   Collecting pyparsing!=3.0.5,>=2.0.2
🐸     Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
🐸   Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
🐸   Installing collected packages: pyparsing, typing-extensions, tomli, setuptools, pycparser, packaging, wheel, setuptools-scm, cffi
🐸       Running setup.py install for cffi: started
🐸       Running setup.py install for cffi: finished with status 'error'
🐸       ERROR: Command errored out with exit status 1:
🐸        command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0el67x9n/cffi_06336e03e43b4f0c848fc2a8fe0c580e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0el67x9n/cffi_06336e03e43b4f0c848fc2a8fe0c580e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c1omn6mq/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-gp9i1_7f/overlay --compile --install-headers /tmp/pip-build-env-gp9i1_7f/overlay/include/python3.9/cffi
🐸            cwd: /tmp/pip-install-0el67x9n/cffi_06336e03e43b4f0c848fc2a8fe0c580e/
🐸       Complete output (45 lines):
🐸  
🐸           No working compiler found, or bogus compiler options passed to
🐸           the compiler from Python's standard "distutils" module.  See
🐸           the error messages above.  Likely, the problem is not related
🐸           to CFFI but generic to the setup.py of any Python package that
🐸           tries to compile C code.  (Hints: on OS/X 10.8, for errors about
🐸           -mno-fused-madd see http://stackoverflow.com/questions/22313407/
🐸           Otherwise, see https://wiki.python.org/moin/CompLangPython or
🐸           the IRC channel #python on irc.libera.chat.)
🐸  
🐸           Trying to continue anyway.  If you are trying to install CFFI from
🐸           a build done in a different context, you can ignore this warning.
🐸  
🐸       running install
🐸       running build
🐸       running build_py
🐸       creating build
🐸       creating build/lib.linux-aarch64-3.9
🐸       creating build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/model.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/error.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/commontypes.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/api.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/lock.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/recompiler.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/__init__.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/verifier.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/cparser.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/_embedding.h -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.9/cffi
🐸       running build_ext
🐸       building '_cffi_backend' extension
🐸       creating build/temp.linux-aarch64-3.9
🐸       creating build/temp.linux-aarch64-3.9/c
🐸       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.9/c/_cffi_backend.o
🐸       error: command 'gcc' failed: No such file or directory
🐸       ----------------------------------------
🐸   ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0el67x9n/cffi_06336e03e43b4f0c848fc2a8fe0c580e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0el67x9n/cffi_06336e03e43b4f0c848fc2a8fe0c580e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c1omn6mq/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-gp9i1_7f/overlay --compile --install-headers /tmp/pip-build-env-gp9i1_7f/overlay/include/python3.9/cffi Check the logs for full command output.
🐸   ----------------------------------------
🐸 WARNING: Discarding https://files.pythonhosted.org/packages/b9/e9/184b8ccce6683b0aa2fbb7ba5683ea4b9c5763f1356347f1312c32e3c66e/argon2-cffi-bindings-21.2.0.tar.gz#sha256=bb89ceffa6c791807d1305ceb77dbfacc5aa499891d2c55661c6459651fc39e3 (from https://pypi.org/simple/argon2-cffi-bindings/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gp9i1_7f/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45' 'setuptools_scm>=6.2' wheel 'cffi>=1.0.1' Check the logs for full command output.
🐸   Downloading argon2-cffi-bindings-21.1.0.tar.gz (1.8 MB)
🐸   Installing build dependencies: started
🐸   Installing build dependencies: finished with status 'error'
🐸   ERROR: Command errored out with exit status 1:
🐸    command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9ujkcvc3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45' 'setuptools_scm>=6.2' wheel 'cffi>=1.0'
🐸        cwd: None
🐸   Complete output (73 lines):
🐸   Collecting setuptools>=45
🐸     Using cached setuptools-65.4.0-py3-none-any.whl (1.2 MB)
🐸   Collecting setuptools_scm>=6.2
🐸     Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
🐸   Collecting wheel
🐸     Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
🐸   Collecting cffi>=1.0
🐸     Using cached cffi-1.15.1.tar.gz (508 kB)
🐸   Collecting pycparser
🐸     Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
🐸   Collecting typing-extensions
🐸     Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
🐸   Collecting tomli>=1.0.0
🐸     Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
🐸   Collecting packaging>=20.0
🐸     Using cached packaging-21.3-py3-none-any.whl (40 kB)
🐸   Collecting pyparsing!=3.0.5,>=2.0.2
🐸     Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
🐸   Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
🐸   Installing collected packages: pyparsing, typing-extensions, tomli, setuptools, pycparser, packaging, wheel, setuptools-scm, cffi
🐸       Running setup.py install for cffi: started
🐸       Running setup.py install for cffi: finished with status 'error'
🐸       ERROR: Command errored out with exit status 1:
🐸        command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cd68c4ec/cffi_923aa3a2bf1c44c6855fc0472f92748f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cd68c4ec/cffi_923aa3a2bf1c44c6855fc0472f92748f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qhr_ucpc/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-9ujkcvc3/overlay --compile --install-headers /tmp/pip-build-env-9ujkcvc3/overlay/include/python3.9/cffi
🐸            cwd: /tmp/pip-install-cd68c4ec/cffi_923aa3a2bf1c44c6855fc0472f92748f/
🐸       Complete output (45 lines):
🐸  
🐸           No working compiler found, or bogus compiler options passed to
🐸           the compiler from Python's standard "distutils" module.  See
🐸           the error messages above.  Likely, the problem is not related
🐸           to CFFI but generic to the setup.py of any Python package that
🐸           tries to compile C code.  (Hints: on OS/X 10.8, for errors about
🐸           -mno-fused-madd see http://stackoverflow.com/questions/22313407/
🐸           Otherwise, see https://wiki.python.org/moin/CompLangPython or
🐸           the IRC channel #python on irc.libera.chat.)
🐸  
🐸           Trying to continue anyway.  If you are trying to install CFFI from
🐸           a build done in a different context, you can ignore this warning.
🐸  
🐸       running install
🐸       running build
🐸       running build_py
🐸       creating build
🐸       creating build/lib.linux-aarch64-3.9
🐸       creating build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/error.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/recompiler.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/commontypes.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/__init__.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/model.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/api.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/cparser.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/verifier.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/lock.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/_embedding.h -> build/lib.linux-aarch64-3.9/cffi
🐸       copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.9/cffi
🐸       running build_ext
🐸       building '_cffi_backend' extension
🐸       creating build/temp.linux-aarch64-3.9
🐸       creating build/temp.linux-aarch64-3.9/c
🐸       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.9/c/_cffi_backend.o
🐸       error: command 'gcc' failed: No such file or directory
🐸       ----------------------------------------
🐸   ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cd68c4ec/cffi_923aa3a2bf1c44c6855fc0472f92748f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cd68c4ec/cffi_923aa3a2bf1c44c6855fc0472f92748f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qhr_ucpc/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-9ujkcvc3/overlay --compile --install-headers /tmp/pip-build-env-9ujkcvc3/overlay/include/python3.9/cffi Check the logs for full command output.
🐸   ----------------------------------------
🐸 WARNING: Discarding https://files.pythonhosted.org/packages/fe/c7/1796c08bc2834424326bec6fffb81bd082cb6c78b278fd0a55b2a09b0454/argon2-cffi-bindings-21.1.0.tar.gz#sha256=5b3c72b092761e9aa8a8335096c409e9d68d127ae64520848d1d9d47459c4650 (from https://pypi.org/simple/argon2-cffi-bindings/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9ujkcvc3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45' 'setuptools_scm>=6.2' wheel 'cffi>=1.0' Check the logs for full command output.
🐸 INFO: pip is looking at multiple versions of sarge to determine which version is compatible with other requirements. This could take a while.
🐸 INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
🐸 INFO: pip is looking at multiple versions of octoprint to determine which version is compatible with other requirements. This could take a while.
🐸 ERROR: Could not find a version that satisfies the requirement argon2-cffi-bindings (from argon2-cffi)
🐸 ERROR: No matching distribution found for argon2-cffi-bindings
 
![Screenshot_20220925-092856](https://user-images.githubusercontent.com/9936033/192133648-0bd02dc7-6ff9-47be-8ad1-28b0306cd89f.png)

**Comment by pnmartinez** [comment]
Same issue as #282

**Comment by feelfreelinux** [comment]
Fixed in https://github.com/feelfreelinux/octo4a/releases/tag/1.1.2 :)
