### ISSUE TITLE
Add Duet2 wifi RepRap driver

### ISSUE THREAD

**Issue by artmanlinux** [feelfreelinux/octo4a#29]
Hello, can you add Duet2 wifi driver. Is not recognized by program. 

Driver  - CDC -
vendor id: 1D50 device id: 60EC

Links of Duet2 wifi vendor id and device id: [https://devicehunt.com/view/type/usb/vendor/1D50/device/60EC](url)

Thank you.  ArtmanLinux

**Comment by feelfreelinux** [comment]
Added in 1.0.0 :)
