### ISSUE TITLE
Pixel 6 showing connection but not connecting

### ISSUE THREAD

**Issue by Digitalpeer1** [feelfreelinux/octo4a#295]
I have a pixel 6 and when I tried to connect it to my ender3V2 it is registering but not connecting pictures below

![unknown](https://user-images.githubusercontent.com/115187094/194404602-fc233e25-f665-43ed-a23f-cf7e1487aa94.png)
![unknown](https://user-images.githubusercontent.com/115187094/194404657-a75663ae-e771-43cf-bf65-c60bf676be55.png)
![Screenshot_20221005-185153](https://user-images.githubusercontent.com/115187094/194404728-77620056-961f-4841-9a14-ab3d5e3a64b4.png)

**Comment by alufers** [comment]
Hi, thanks for trying octo4a!

Please add an "Additional serial port" in the Octoprint settings: ` /dev/ttyOcto4a`, and use it as the serial port. 

![image](https://user-images.githubusercontent.com/5400940/194433435-a53492d3-3848-4953-89a5-4bab97d23d0e.png)

**Comment by Digitalpeer1** [comment]
Hi, how do i do that?
