### ISSUE TITLE
X96 mini

### ISSUE THREAD

**Issue by lstremfelj** [feelfreelinux/octo4a#323]
Any chance to get this working on a X96 mini? 
I can install 1.1.2 version apk. Then it opens a prompt - there is no existing instalation detected when i confirm install Octoprint it reports missing storage permision briefly then it opens promt to alow acces for video and audio and goes to install boot strap where it hangs or crashes. 
X96 is runign on android 7.1.2  with 2 gb ram 8 gb rom  4core 64 bit processor think amilogic s905w.

**Comment by alufers** [comment]
Try the newer verisons. If the problem persists please open a new issue.
