### ISSUE TITLE
Need a little help with BLU View 2

### ISSUE THREAD

**Issue by RickzFPV** [feelfreelinux/octo4a#329]
So after doing some extensive research I installed termux on this BLU View 2 phone and I can finally ssh into it but now when I go to install pip3 it won't let me is there something I need to do different with Termux that I didn't have to do with my lenovo Tablet.  My tablet is running perfectly with octo4A and would like to get this phone running the same.  Any help will be much appreciated.

**Comment by RickzFPV** [comment]
I am wondering if someone can help me I am able now to ssh into the blue view 2 phone everything communicates fine but when I enter in the commands for the fix it can't find the packages

**Comment by thomasbra1** [comment]
If you have the B131DL (Android 11) it won't install and just give a corrupted message.   I have a B130DL working fine with A10 but the B131DL with A11 won't install properly.  Been keeping a eye here to see if a newer version will pop up with a fix.

**Comment by RickzFPV** [comment]
Yeah Mine are the B131 DL's and mine are doing the same thing and not installing properly I am gonna just have to wait on these also in hope of a fix or a new version release to use them.  for now I am just using them as touch interfaces on the 2 printers I have raspberry PI's installed on.

**Comment by cjsz450** [comment]
Any word on an update for the B131DL?

**Comment by RickzFPV** [comment]
I have no idea I was never able to even ssh into one on android 11

**Comment by alufers** [comment]
Should work with 1.2.4
