### ISSUE TITLE
Android KitKat 4.4 (old Android TV with tablet version)

### ISSUE THREAD

**Issue by axute** [feelfreelinux/octo4a#340]
I was very pleased to see that the app was still starting to install on the old device, however this crashed after the Octoprint unpacking step.
I think he wants to install additional packages afterwards, dependencies. But that doesn't happen anymore, the app closes immediately, so I can't see/export the log.
Do you have any idea what might be too old?
In the storage section I find under `Android/data/com.octo4a/extensions` only `ttyd` with some scripts.

**Comment by alufers** [comment]
Sorry, can't help you without a log. If you can yo ucan use adb to get it.
