### ISSUE TITLE
Unknown serial driver Artillery Sidewinder X2

### ISSUE THREAD

**Issue by windowslucker1121** [feelfreelinux/octo4a#343]
Hey hey,
i wanted to setup octoprint on my Xiaomi Mi 9 but it seems im stuck on the following screen:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/59010961/211427349-8e8a81b5-6df7-4246-af6f-97531dae0b6c.jpg">
I tried every serial driver(especially the CDC driver) on the "ARTILLERY_RUBY CDC in FS Mode" and every baudrate which was available in octoprint but i just get the error messages "no serial port found"
<img width="250" alt="image" src="https://user-images.githubusercontent.com/59010961/211427451-01d34474-6e04-4b61-a305-6ab69ab53271.png">

I tried the latest apk, which is 1.1.2 and i builded the apk myself off the latest master branch which didnt worked either.

am i missing something?

Greetings and keep up the good work!

**Comment by Filo301** [comment]
I had problem with stock mi9, give up pretty fast and flashed pixel experience. Then worked without any problem

**Comment by windowslucker1121** [comment]
> I had problem with stock mi9, give up pretty fast and flashed pixel experience. Then worked without any problem. You should check which model of usb-ttl converter is inside your printer (if any)


Like you suggested, i installed the Pixel Rom on my Mi 9 and installed my selfbuild APK onto the device, sadly the same behaviour as described above.
I tried it with different USB hubs but sadly its not working.

**Comment by dohamann** [comment]
I'm currently in a similar situation, trying to get my Sidewinder X2 to work with Octo4a and though I'm a lot further down the line than @windowslucker1121, I can only recommend to not use Octo4a. It's not nearly stable enough to use and causes more issues than it's worth. There are barely any resources to look up. I really like the concept but reality just doesn't hold up.

Abandon ship. Get a pi.

**Comment by dohamann** [comment]
To actually respond to your issue: It's a bit weird that the app recognizes the device itself but doesn't offer any serial port. Have you tried having both the printer and your smartphone running and then remove all cables and put them back together?

May sound dumb, but I recall that I had an issue reconnecting after having rebooted the phone and for some reason it didn't work. There's a dialog in android  (at least the version of it that I'm using) that requests permission for the app to use the USB device, which I have to check every single time. It wouldn't work until I removed the cable from the phone. Re-plugging the printer-side of the cable didn't work.

![Here's what it looks like on my phone when it works](https://user-images.githubusercontent.com/12189053/212309805-246fdd64-1895-4b84-8fa2-8b5177f48815.png). 
![OctoPrint](https://user-images.githubusercontent.com/12189053/212310289-4a184c35-2bb5-482e-a8f7-e11f5b5eb723.png).


CDC sounds about right. Auto-detection chooses a baud rate of 115200. But I do have issues with prints stuttering which leaves nasty printing artifacts, so I obviously can't vouch for these parameters actually working. But I guess being connected to the printer and being able to print is a big step in the right direction from where you are right now.

**Comment by windowslucker1121** [comment]
to update on you guys:
@dohamann yes, i retried it multiple times and yes i granted the permission for accessing the usb device.
and lastly i followed your advice and bought an used rpi 3 b, which is working perfectly fine. 
fiddling around with that for 2 days was definitly not worth it :D

**Comment by dohamann** [comment]
@windowslucker1121 In this case I really hate to be right. Anyway, have fun with your new toy!
