### ISSUE TITLE
SSH password not updating

### ISSUE THREAD

**Issue by PeriodicOccupancy** [feelfreelinux/octo4a#346]
IP address on my phone changed, forgot the passwords I had setup the server with so changed the SSH password in app, shutdown and restarted the app, tried to SSH in and it's telling me permission denied, despite triple checking its the same as the password set in the app.

**Comment by MurKit** [comment]
it's probably because you're trying the **root** username, and octo4a allows you to login as **octoprint**.

However it'd be nice to login as root.
