### ISSUE TITLE
Every file I download gets corrupted 

### ISSUE THREAD

**Issue by Rikbraspenning** [feelfreelinux/octo4a#349]
On my Nokia G20 is that the problem

**Comment by Mr2nR** [comment]
Same issue on Samsung  tab s2.  Says octoprint installation is corrupted.

**Comment by davidbrownds** [comment]
Same on Note w0

**Comment by Mr2nR** [comment]
found the fix -- https://github.com/feelfreelinux/octo4a/issues/325#issuecomment-1345426359

**Comment by alufers** [comment]
Should be fixed in >= 1.2.1.
