### ISSUE TITLE
Can not connect to SSH with Putty

### ISSUE THREAD

**Issue by davidbrownds** [feelfreelinux/octo4a#350]
I tried to follow the steps to fix the corruption issues from #325 

But Putty or Windows 10 PowerShell will not take password.  I tried leaving it blank and setting to 1234.   Can anyone help me with this?

**Comment by TechWithMikeD** [comment]
You didn't tell us what is actually happening. Is it telling you the password was wrong, or just a closed connection when trying to SSH?

**Comment by alufers** [comment]
Did you set the port with the `-p 8022` option?

Anyway the corruption issue has been fixed in 1.2.0
