### ISSUE TITLE
Printer Serial won't connect while powered on, but works flawless when printer is power off

### ISSUE THREAD

**Issue by Oponnn** [feelfreelinux/octo4a#351]
![PXL_20230118_174958995~2](https://user-images.githubusercontent.com/122370926/213256935-5c14e6f6-a9f1-4461-af23-9ee81537e4d8.jpg)
 has the title says, octoprint recognizes the printer flawlessly when the printer is powered down and displays the serial connection, but as soon as I turn the printer on the server has trouble connecting to it,  and when it does connect it loses connection intermittently and makes prints fail. I tried the electrical tape idea to block the 5v pin on the usb but then octoprint does not pick up the printer at all when its powered down. Any help would be greatly appreciated. 

Edit1: it looks like its having trouble dealing with both cables aswell, im running a USB C splitter to USB and USBC females and one is plugged in for charging the usb goes to printer. Phone im using is a LG G5

**Comment by alufers** [comment]
Sorry, this looks like an issue specific to this phone/your setup. I cannot really help you as I don't have it. Trying diffrent adapters might help.
