### ISSUE TITLE
Setting up octoprint with webcam?

### ISSUE THREAD

**Issue by indieshack** [feelfreelinux/octo4a#352]
Octoprint is running fine on my Android device, which has two USBs out; one USB is connected to the cable to my printer, leaving the other USB input free. The other USB I could use for my webcam but octoprint thinks my webcam is a printer. Is there any way to connect the webcam to octoprint and have octoprint know it's a cam and not another printer connection?

**Comment by alufers** [comment]
Duplicate of https://github.com/feelfreelinux/octo4a/issues/95
