### ISSUE TITLE
Application language localization

### ISSUE THREAD

**Issue by tkwhd123** [feelfreelinux/octo4a#356]
Hello, I am a S.Korean user. I would like to contribute to Korean localization translation of this application. How can I do it?

You can continue the conversation at tkwhd123@naver.com.

**Comment by alufers** [comment]
You can start by translating this file: https://github.com/feelfreelinux/octo4a/blob/master/app/app/src/main/res/values/strings.xml

If you do so, I can integrate it another language in the app.
