### ISSUE TITLE
Massive browser RAM&CPU usage the moment webcam turned on

### ISSUE THREAD

**Issue by Ethan-Ming** [feelfreelinux/octo4a#368]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/36059080/217015260-9b17b5d2-c551-4bee-9ab2-c965cd21e998.png">

I have tried multiple app version, same behavior even on fresh installation without any plugin
it even freezes mobile browser, it doesn't matter which browser and what machine I'm accessing it from as long as i'm requesting camera stream. It will freeze the browser tab, sometime took down whole browser 

Surprisingly, the printer can still print while all this is happening

Pixel 2

**Comment by univers-ally** [comment]
Similarly happens to my S8. It actually crashed my phone and stopped a print due to the phone killing the process for overloading the CPU.

**Comment by Gorpokki** [comment]
Happening on my Galaxy S10+. Cannot use octoprint without turning off the camera server.

**Comment by Gorpokki** [comment]
Resolved for me after a complete reboot of my Android
