### ISSUE TITLE
Is it possible to install TailScale?

### ISSUE THREAD

**Issue by Androxilogin** [feelfreelinux/octo4a#374]
Been using this on my Pi Zero the past few nights and was hoping this was an option but all I get is the error:

+ rc-update add tailscale
sh: rc-update: not found

**Comment by lmichoux** [comment]
If you need a specific tool you can install it using the Alpine package manager.
Octo4a is running on alpine linux distribution (https://docs.alpinelinux.org)
Here is the command to install tailscale:
#  apk  add tailscale

**Comment by alufers** [comment]
Instaling tailscae through the built in shell is not recommended (I don't think it will even work, as it needs to create a TUN device).

You should use this on Android:  https://play.google.com/store/apps/details?id=com.tailscale.ipn&hl=pl&gl=IT

**Comment by Androxilogin** [comment]
> Instaling tailscae through the built in shell is not recommended (I don't think it will even work, as it needs to create a TUN device).
> 
> You should use this on Android: https://play.google.com/store/apps/details?id=com.tailscale.ipn&hl=pl&gl=IT

That's only compatible with certain versions of Android.
