### ISSUE TITLE
Suggestion: Expand information and links for charging and compatiblity on Wiki

### ISSUE THREAD

**Issue by sharpie7** [feelfreelinux/octo4a#390]
This comment https://github.com/feelfreelinux/octo4a/issues/386#issuecomment-1481106370 contains very useful info. 

Can I suggest you add the information and links to the Wiki, perhaps on this page:
https://github.com/feelfreelinux/octo4a/wiki/Connecting-to-printer-via-OTG,-simultaneous-charging

**Comment by alufers** [comment]
Added.
