### ISSUE TITLE
ERROR: unable to select packages: p7zip (no such package): required by: world[p7zip].....Error Attached.

### ISSUE THREAD

**Issue by inv4dor** [feelfreelinux/octo4a#392]
I have a galaxy tab 3 and galaxy S5, both devices have the same error.

![octo4 fail](https://user-images.githubusercontent.com/119398518/227714623-bffd897c-a78a-4b57-b305-59e4681b46f0.jpg)

**Comment by alufers** [comment]
I see, this must have been introduced by a bugfix I added yesterday. Please try 1.2.2

**Comment by alufers** [comment]
Could you check 1.2.3?

**Comment by alufers** [comment]
I've tested 1.2.4 on a SM-J320FN and it appears to fix this particular issue.
