### ISSUE TITLE
I'm getting error when installing. 

### ISSUE THREAD

**Issue by gadonner** [feelfreelinux/octo4a#473]
This is not my first time but I'm stuck right now.

gustaf@gustaf-laptop:~$ ssh root@192.186.0.24 -p 8022
ssh root@192.168.0.24 -p 8022
ssh: connect to host 192.186.0.24 port 8022: Connection timed out
gustaf@gustaf-laptop:~$ ssh root@192.168.0.24 -p 8022
root@192.168.0.24's password: 
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <https://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

localhost:~# cd octoprint
-ash: cd: can't cd to octoprint: No such file or directory
localhost:~# dir
-ash: dir: not found
localhost:~# pip3 install --upgrade setuptools wheel tornado --no-cache-dir

Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (69.5.1)
Requirement already satisfied: wheel in /usr/lib/python3.10/site-packages (0.43.0)
Requirement already satisfied: tornado in /usr/lib/python3.10/site-packages (6.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
localhost:~# 
localhost:~# curl -s https://raw.githubusercontent.com/feelfreelinux/octo4a/mast
er/scripts/setup-octo4a.sh | bash -s
OK: 390 MiB in 148 packages
Collecting packaging
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Installing collected packages: packaging
Successfully installed packaging-24.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting https://github.com/feelfreelinux/octo4a-argon2-mock/archive/main.zip
  Using cached https://github.com/feelfreelinux/octo4a-argon2-mock/archive/main.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
localhost:~# unzip octoprint.zip
-ash: unzip: Permission denied
localhost:~# cd octo*
-ash: cd: can't cd to octoprint.zip: Not a directory
localhost:~# cd Octo*
localhost:~/OctoPrint-OctoPrint-fed2dd7# pip3 install Octoprint
Collecting Octoprint
  Using cached OctoPrint-1.10.0-py2.py3-none-any.whl (3.4 MB)
Collecting Flask-Login<0.7,>=0.6.3
  Using cached Flask_Login-0.6.3-py3-none-any.whl (17 kB)
Collecting psutil<6,>=5.9.8
  Using cached psutil-5.9.8.tar.gz (503 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyYAML<7,>=6.0.1
  Using cached PyYAML-6.0.1.tar.gz (125 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting websocket-client==1.6.1
  Using cached websocket_client-1.6.1-py3-none-any.whl (56 kB)
Collecting pylru<2,>=1.2.1
  Using cached pylru-1.2.1-py3-none-any.whl (16 kB)
Collecting sentry-sdk<2,>=1.40.0
  Using cached sentry_sdk-1.45.0-py2.py3-none-any.whl (267 kB)
Collecting requests<3,>=2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting class-doc<0.3,>=0.2.6
  Using cached class_doc-0.2.6-py3-none-any.whl (4.7 kB)
Collecting emoji<3,>=2.10.1
  Using cached emoji-2.11.1-py2.py3-none-any.whl (433 kB)
Collecting werkzeug<2.3,>=2.2.3
  Using cached Werkzeug-2.2.3-py3-none-any.whl (233 kB)
Collecting pytz
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting zeroconf~=0.127
  Using cached zeroconf-0.132.2.tar.gz (170 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting zipstream-ng<2.0.0,>=1.7.1
  Using cached zipstream_ng-1.7.1-py3-none-any.whl (22 kB)
Collecting passlib<2,>=1.7.4
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting argon2-cffi>=23.1.0
  Using cached argon2_cffi-23.1.0-py3-none-any.whl (15 kB)
Collecting tornado<6.3,>=6.2
  Using cached tornado-6.2.tar.gz (504 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydantic==1.10.12
  Using cached pydantic-1.10.12-py3-none-any.whl (158 kB)
Collecting filetype<2,>=1.2.0
  Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting pkginfo<2,>=1.9.6
  Using cached pkginfo-1.10.0-py3-none-any.whl (30 kB)
Collecting frozendict<3,>=2.4.0
  Using cached frozendict-2.4.2.tar.gz (315 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: wheel in /usr/lib/python3.10/site-packages (from Octoprint) (0.43.0)
Requirement already satisfied: regex in /usr/lib/python3.10/site-packages (from Octoprint) (2022.10.31)
Collecting Flask-Limiter<4,>=3.5.0
  Using cached Flask_Limiter-3.6.0-py3-none-any.whl (28 kB)
Collecting blinker<1.7.0,>=1.6.3
  Using cached blinker-1.6.3-py3-none-any.whl (13 kB)
Collecting markdown<3.5,>=3.4.4
  Using cached Markdown-3.4.4-py3-none-any.whl (94 kB)
Collecting netaddr<0.9,>=0.8
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting wrapt<1.16,>=1.15
  Using cached wrapt-1.15.0-py3-none-any.whl (22 kB)
Collecting Babel<2.13,>=2.12.1
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Collecting semantic-version<3,>=2.10.0
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting pyserial<4,>=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting watchdog<3,>=2.3.1
  Using cached watchdog-2.3.1.tar.gz (123 kB)
  Preparing metadata (setup.py) ... done
Collecting flask<2.3,>=2.2.3
  Using cached Flask-2.2.5-py3-none-any.whl (101 kB)
Collecting feedparser<7,>=6.0.11
  Using cached feedparser-6.0.11-py3-none-any.whl (81 kB)
Collecting sarge==0.1.7.post1
  Using cached sarge-0.1.7.post1-py2.py3-none-any.whl (18 kB)
Collecting Flask-Assets<3,>=2.1.0
  Using cached Flask_Assets-2.1.0-py3-none-any.whl (8.5 kB)
Collecting OctoPrint-FirmwareCheck>=2021.10.11
  Using cached OctoPrint_FirmwareCheck-2021.10.11-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from Octoprint) (69.5.1)
Collecting colorlog<7,>=6.7.0
  Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
Collecting future<1,>=0.18.3
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask-Babel<4,>=3.1.0
  Using cached flask_babel-3.1.0-py3-none-any.whl (9.6 kB)
Collecting OctoPrint-PiSupport>=2023.10.10
  Using cached OctoPrint_PiSupport-2023.10.10-py2.py3-none-any.whl (35 kB)
Collecting netifaces2<0.1,>=0.0.21
  Using cached netifaces2-0.0.22-cp37-abi3-musllinux_1_1_armv7l.whl (1.3 MB)
Collecting pathvalidate<3,>=2.5.2
  Using cached pathvalidate-2.5.2-py3-none-any.whl (20 kB)
Collecting unidecode
  Using cached Unidecode-1.3.8-py3-none-any.whl (235 kB)
Collecting OctoPrint-FileCheck>=2021.2.23
  Using cached OctoPrint_FileCheck-2024.3.27-py2.py3-none-any.whl (31 kB)
Collecting cachelib<0.11,>=0.10.2
  Using cached cachelib-0.10.2-py3-none-any.whl (18 kB)
Collecting Click<9,>=8.1.7
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting argon2-cffi-bindings
  Using cached argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
      Collecting setuptools>=45
        Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Collecting cffi>=1.0.1
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting tomli>=1
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting packaging>=20
        Using cached packaging-24.0-py3-none-any.whl (53 kB)
      Collecting typing-extensions
        Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
      Collecting pycparser
        Using cached pycparser-2.22-py3-none-any.whl (117 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for cffi (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [74 lines of output]
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
            compilation terminated.
            gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
            compilation terminated.
      
                No working compiler found, or bogus compiler options passed to
                the compiler from Python's standard "distutils" module.  See
                the error messages above.  Likely, the problem is not related
                to CFFI but generic to the setup.py of any Python package that
                tries to compile C code.  (Hints: on OS/X 10.8, for errors about
                -mno-fused-madd see http://stackoverflow.com/questions/22313407/
                Otherwise, see https://wiki.python.org/moin/CompLangPython or
                the IRC channel #python on irc.libera.chat.)
      
                Trying to continue anyway.  If you are trying to install CFFI from
                a build done in a different context, you can ignore this warning.
      
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-cpython-310
            creating build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/__init__.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_imp_emulation.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/api.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/backend_ctypes.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/commontypes.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/cparser.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/error.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/ffiplatform.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/lock.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/model.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/recompiler.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/setuptools_ext.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/vengine_gen.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/verifier.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_cffi_include.h -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/parse_c_type.h -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_embedding.h -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpython-310/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-cpython-310
            creating build/temp.linux-armv7l-cpython-310/src
            creating build/temp.linux-armv7l-cpython-310/src/c
            gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.10 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-310/src/c/_cffi_backend.o
            gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
            compilation terminated.
            error: command 'gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
localhost:~/OctoPrint-OctoPrint-fed2dd7# sudo update
-ash: sudo: not found
localhost:~/OctoPrint-OctoPrint-fed2dd7# cd
localhost:~# dir
-ash: dir: not found
localhost:~# sudo update octoprint
-ash: sudo: not found
localhost:~# cd Octo*
localhost:~/OctoPrint-OctoPrint-fed2dd7# pip3 install .
Processing /root/OctoPrint-OctoPrint-fed2dd7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting future<1,>=0.18.3
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... done
Collecting pytz
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting filetype<2,>=1.2.0
  Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting Click<9,>=8.1.7
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting feedparser<7,>=6.0.11
  Using cached feedparser-6.0.11-py3-none-any.whl (81 kB)
Collecting sarge==0.1.7.post1
  Using cached sarge-0.1.7.post1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: regex in /usr/lib/python3.10/site-packages (from OctoPrint==1.10.0) (2022.10.31)
Collecting passlib<2,>=1.7.4
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting Flask-Login<0.7,>=0.6.3
  Using cached Flask_Login-0.6.3-py3-none-any.whl (17 kB)
Collecting markdown<3.5,>=3.4.4
  Using cached Markdown-3.4.4-py3-none-any.whl (94 kB)
Collecting pyserial<4,>=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting pydantic==1.10.12
  Using cached pydantic-1.10.12-py3-none-any.whl (158 kB)
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from OctoPrint==1.10.0) (69.5.1)
Collecting cachelib<0.11,>=0.10.2
  Using cached cachelib-0.10.2-py3-none-any.whl (18 kB)
Collecting argon2-cffi>=23.1.0
  Using cached argon2_cffi-23.1.0-py3-none-any.whl (15 kB)
Collecting zeroconf~=0.127
  Using cached zeroconf-0.132.2.tar.gz (170 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting netaddr<0.9,>=0.8
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting Babel<2.13,>=2.12.1
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Collecting psutil<6,>=5.9.8
  Using cached psutil-5.9.8.tar.gz (503 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Flask-Limiter<4,>=3.5.0
  Using cached Flask_Limiter-3.6.0-py3-none-any.whl (28 kB)
Collecting semantic-version<3,>=2.10.0
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting flask<2.3,>=2.2.3
  Using cached Flask-2.2.5-py3-none-any.whl (101 kB)
Collecting OctoPrint-PiSupport>=2023.10.10
  Using cached OctoPrint_PiSupport-2023.10.10-py2.py3-none-any.whl (35 kB)
Collecting pylru<2,>=1.2.1
  Using cached pylru-1.2.1-py3-none-any.whl (16 kB)
Collecting zipstream-ng<2.0.0,>=1.7.1
  Using cached zipstream_ng-1.7.1-py3-none-any.whl (22 kB)
Collecting wrapt<1.16,>=1.15
  Using cached wrapt-1.15.0-py3-none-any.whl (22 kB)
Collecting pathvalidate<3,>=2.5.2
  Using cached pathvalidate-2.5.2-py3-none-any.whl (20 kB)
Collecting watchdog<3,>=2.3.1
  Using cached watchdog-2.3.1.tar.gz (123 kB)
  Preparing metadata (setup.py) ... done
Collecting OctoPrint-FileCheck>=2021.2.23
  Using cached OctoPrint_FileCheck-2024.3.27-py2.py3-none-any.whl (31 kB)
Collecting websocket-client==1.6.1
  Using cached websocket_client-1.6.1-py3-none-any.whl (56 kB)
Collecting frozendict<3,>=2.4.0
  Using cached frozendict-2.4.2.tar.gz (315 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests<3,>=2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting pkginfo<2,>=1.9.6
  Using cached pkginfo-1.10.0-py3-none-any.whl (30 kB)
Collecting class-doc<0.3,>=0.2.6
  Using cached class_doc-0.2.6-py3-none-any.whl (4.7 kB)
Collecting netifaces2<0.1,>=0.0.21
  Using cached netifaces2-0.0.22-cp37-abi3-musllinux_1_1_armv7l.whl (1.3 MB)
Collecting unidecode
  Using cached Unidecode-1.3.8-py3-none-any.whl (235 kB)
Collecting Flask-Babel<4,>=3.1.0
  Using cached flask_babel-3.1.0-py3-none-any.whl (9.6 kB)
Collecting PyYAML<7,>=6.0.1
  Using cached PyYAML-6.0.1.tar.gz (125 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting blinker<1.7.0,>=1.6.3
  Using cached blinker-1.6.3-py3-none-any.whl (13 kB)
Collecting Flask-Assets<3,>=2.1.0
  Using cached Flask_Assets-2.1.0-py3-none-any.whl (8.5 kB)
Collecting OctoPrint-FirmwareCheck>=2021.10.11
  Using cached OctoPrint_FirmwareCheck-2021.10.11-py2.py3-none-any.whl (33 kB)
Collecting werkzeug<2.3,>=2.2.3
  Using cached Werkzeug-2.2.3-py3-none-any.whl (233 kB)
Collecting tornado<6.3,>=6.2
  Using cached tornado-6.2.tar.gz (504 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sentry-sdk<2,>=1.40.0
  Using cached sentry_sdk-1.45.0-py2.py3-none-any.whl (267 kB)
Requirement already satisfied: wheel in /usr/lib/python3.10/site-packages (from OctoPrint==1.10.0) (0.43.0)
Collecting emoji<3,>=2.10.1
  Using cached emoji-2.11.1-py2.py3-none-any.whl (433 kB)
Collecting colorlog<7,>=6.7.0
  Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting argon2-cffi-bindings
  Using cached argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
      Collecting setuptools>=45
        Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Collecting cffi>=1.0.1
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting typing-extensions
        Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
      Collecting tomli>=1
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting packaging>=20
        Using cached packaging-24.0-py3-none-any.whl (53 kB)
      Collecting pycparser
        Using cached pycparser-2.22-py3-none-any.whl (117 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for cffi (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [74 lines of output]
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            Package libffi was not found in the pkg-config search path.
            Perhaps you should add the directory containing `libffi.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'libffi', required by 'virtual:world', not found
            gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
            compilation terminated.
            gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
            compilation terminated.
      
                No working compiler found, or bogus compiler options passed to
                the compiler from Python's standard "distutils" module.  See
                the error messages above.  Likely, the problem is not related
                to CFFI but generic to the setup.py of any Python package that
                tries to compile C code.  (Hints: on OS/X 10.8, for errors about
                -mno-fused-madd see http://stackoverflow.com/questions/22313407/
                Otherwise, see https://wiki.python.org/moin/CompLangPython or
                the IRC channel #python on irc.libera.chat.)
      
                Trying to continue anyway.  If you are trying to install CFFI from
                a build done in a different context, you can ignore this warning.
      
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-cpython-310
            creating build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/__init__.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_imp_emulation.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/api.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/backend_ctypes.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/commontypes.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/cparser.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/error.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/ffiplatform.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/lock.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/model.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/recompiler.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/setuptools_ext.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/vengine_gen.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/verifier.py -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_cffi_include.h -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/parse_c_type.h -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_embedding.h -> build/lib.linux-armv7l-cpython-310/cffi
            copying src/cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpython-310/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-cpython-310
            creating build/temp.linux-armv7l-cpython-310/src
            creating build/temp.linux-armv7l-cpython-310/src/c
            gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.10 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-310/src/c/_cffi_backend.o
            gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
            compilation terminated.
            error: command 'gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
localhost:~/OctoPrint-OctoPrint-fed2dd7#

**Comment by hounslg** [comment]
The issue is related to the new release of Octoprint (1.10).  A fix or work around is required.

**Comment by gadonner** [comment]
Should I try an older version?

**Comment by hounslg** [comment]
You'll need to wait for an update to the app unfortunately.  It downloads the latest version of Octoprint.

**Comment by gadonner** [comment]
Installed new release. Corrupted install but seems to work.

**Comment by gadonner** [comment]
Sorry. When I restarted phone it was still install corrupted

**Comment by feelfreelinux** [comment]
Released https://github.com/feelfreelinux/octo4a/releases/tag/2.0.0 which should resolve this issue :)
