### ISSUE TITLE
Install failed on Android 7.1.2

### ISSUE THREAD

**Issue by LOWTANG1993** [feelfreelinux/octo4a#52]
![137710735-27b9036d-9cc5-4aba-8876-b0e00035ae77](https://user-images.githubusercontent.com/93347184/139319327-84710d7f-8b80-4fec-83b9-68dc44122781.jpg)

The phone is Meizu’s note6, the Android version is 7.1.2, and 1.0.1 is installed. It always shows 150% and it cannot continue, but I successfully installed 0.0.5 and it runs successfully.

**Comment by feelfreelinux** [comment]
Please try to reinstall the app, this issue happens sporadically when the phone can't react github.com at given moment

**Comment by Pcbrenner** [comment]
the same thing happened to me , but i figured out that connecting the phone to my fritzbox guest-wifi fixes the error for me.

**Comment by LOWTANG1993** [comment]
Thank you for your recovery! I have successfully installed 1.0.3

**Comment by LOWTANG1993** [comment]
Thank you for your reply! I have successfully installed 1.0.3
