### ISSUE TITLE
URL of camera server?

### ISSUE THREAD

**Issue by mtsouris81** [feelfreelinux/octo4a#53]
I can't find any documentation on the camera server URL. When octoprint sever is running, i see the IP address / port, but when my camera server is running, i don't see a URL, just an indication that it is running.

**Comment by feelfreelinux** [comment]
Hi! It's 
address:5001/mjpeg - mjpeg stream
address:5001/snapshot - camera snapshot

**Comment by feelfreelinux** [comment]
Added to wiki in
https://github.com/feelfreelinux/octo4a/wiki/FAQ#i-want-to-manually-access-the-camera-server-how-can-i-do-that
