### ISSUE TITLE
App Crash when no network during install

### ISSUE THREAD

**Issue by assignUser** [feelfreelinux/octo4a#6]
nexus 4,  7.1.1 Hellspawn Kernel

If you try to start the installation of octoprint from within the app it will crash if there is no network/wifi connection.

**Comment by tavdog** [comment]
I've seen this too on Moto G5

**Comment by feelfreelinux** [comment]
network check implemented in https://github.com/feelfreelinux/octo4a/commit/57803a3ebe1012d4afb74f9a564ea8507ba52ebd

Thanks for reporting this :)
