### ISSUE TITLE
Camera not working in OctoPrint UI

### ISSUE THREAD

**Issue by SirDragonClaw** [feelfreelinux/octo4a#60]
I assume it is misconfigured as it shows up in the app just fine. Is the Camera Server Stream URL '/webcam/?action=stream' ?

If not, what should it be set to?

**Comment by feelfreelinux** [comment]
Hi! The camera address is:

`phone_ip:5001/mjpeg` for stream
`phone_ip:5001/snapshot` for jpeg snapshot

**Comment by SirDragonClaw** [comment]
Yep works perfectly. I am guessing this would have been the default if I had not loaded a backup taken from an octoprint install. Thanks for the info.
