### ISSUE TITLE
Camera frame issue

### ISSUE THREAD

**Issue by ownyzo** [feelfreelinux/octo4a#76]
Hello,
Runnig octo4a on huawei p40lite, everything works great except the camera. I'm getting 1 frame per minute, working with the settings (resolution, FPS limit) doesn't help. What i noticed is that some times the whole control page freezes, in the same time no issue on the phone side(running like a hot knife through butter).

Anything that i'm missing?
Thanks!

**Comment by Kendrik01** [comment]
Try a different browser.  I had similar (the same?) issues with Firefox (on a Galaxy S9+) but it worked fine on MS Edge.
