### ISSUE TITLE
Not sure where to find API Key

### ISSUE THREAD

**Issue by IZZYGamez361** [feelfreelinux/octo4a#86]
I have the OctoPrint plugin for Ultimaker Cura 4.12.0. I have all set and ready but this API thing is stopping me.

**Comment by impatman** [comment]
This is not related octo4a, this is for general Octoprint. https://all3dp.com/2/cura-octoprint-plugin-connection/

**Comment by IZZYGamez361** [comment]
I tried getting the API Key but that page never loads.

**Comment by IZZYGamez361** [comment]
> This is not related octo4a, this is for general Octoprint. https://all3dp.com/2/cura-octoprint-plugin-connection/

I tried using the IP given to find the API Key, but it just sits and buffers. Is that not a fault of octo4a or OctoPrint?

**Comment by alufers** [comment]
Hey! This indeed looks like a problem with octoprint and not octo4a.

If it turns out that octoprint doesn't even start for you because of an octo4a issue, please open a new issue.
